version: 2

seeds:
  - name: customers  # Nazwa seeda musi odpowiadać nazwie pliku CSV (bez rozszerzenia)
    config:
      column_types:
        customer_id: bigint       # Zgodnie z sugestią sniffera (BIGINT zamiast INTEGER)
        first_name: varchar
        last_name: varchar
        email: varchar
        phone_number: varchar
        address: varchar
        city: varchar
        country: varchar
        postal_code: varchar      # Często kody pocztowe lepiej trzymać jako tekst
        age: integer
        gender: varchar
        registration_date: date   # Możesz potrzebować określić format daty, jeśli nie jest standardowy
        related_accounts: varchar # Kluczowa zmiana: Wymuszenie typu tekstowego (VARCHAR)