# Użycie lżejszego executora i wyłączenie Redisa
executor: KubernetesExecutor
redis:
  enabled: false

# enable embeded PostgreSQL
postgresql:
  enabled: true
webserver:
  enabled: true
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false

migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

scheduler:
  startupProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    failureThreshold: 6
    timeoutSeconds: 120
  extraVolumes:
    - name: dags
      hostPath:
        path: /opt/airflow/dags/
        type: Directory
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
      readOnly: true

dagProcessor:
  extraVolumes:
    - name: dags
      hostPath:
        path: /opt/airflow/dags/
        type: Directory
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
      readOnly: true

workers:
  env:
#    - name: AIRFLOW_CONN_HTTP_DUMMYJSON
#      value: '{"conn_type": "http_dummyjson","host": "https://dummyjson.com","conn_type": "http"}'
#    - name: AIRFLOW_CONN_FS_DEFAULT
#      value: '{"conn_type": "fs_default","conn_type": "fs"}'
#    - name: _PIP_ADDITIONAL_REQUIREMENTS
#      value: "duckdb faker"
  extraVolumes:
    - name: dags
      hostPath:
        path: /opt/airflow/dags
        type: Directory
    - name: data
      hostPath:
        path: /opt/airflow/data
        type: Directory
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
      readOnly: true
    - name: data
      mountPath: /opt/airflow/data
      readOnly: false

airflow:
  connections:
    - conn_id: http_dummyjson
      conn_type: http
      host: https://dummyjson.com/

    - conn_id: local_fs
      conn_type: fs

apiServer:
  startupProbe:
    initialDelaySeconds: 300
    periodSeconds: 10
    failureThreshold: 6
    timeoutSeconds: 300
  extraVolumes:
    - name: dags
      hostPath:
        path: /opt/airflow/dags/
        type: Directory
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
      readOnly: true

