import pendulum
from airflow.datasets import Dataset
from airflow.decorators import dag, task

# 1. Define our asset based on a physical file
# We use the file:// scheme
PHYSICAL_DATA_FILE = Dataset("file:///opt/airflow/dags/shared_data.txt")

# ==========================================
# PRODUCER DAG
# ==========================================
@dag(
    dag_id="producer_physical_file",
    schedule=None, # Triggered manually (for demo purposes)
    start_date=pendulum.datetime(2023, 1, 1, tz="UTC"),
    catchup=False,
    tags=["demo", "assets", "producer", "module 007"]
)
def producer_physical_dag():

    # Inform Airflow: This task updates the PHYSICAL_DATA_FILE
    @task(outlets=[PHYSICAL_DATA_FILE])
    def generate_data():
        file_path = "/opt/airflow/dags/shared_data.txt"
        with open(file_path, "w") as f:
            f.write("This is secret data generated by the producer!")
        print(f"Data successfully written to {file_path}")

    generate_data()

producer_physical_dag()


# ==========================================
# CONSUMER DAG
# ==========================================
@dag(
    dag_id="consumer_physical_file",
    schedule=[PHYSICAL_DATA_FILE], # Instead of CRON, we listen to our Asset!
    start_date=pendulum.datetime(2023, 1, 1, tz="UTC"),
    catchup=False,
    tags=["demo", "assets", "consumer", "module 007"]
)
def consumer_physical_dag():

    @task
    def process_data():
        file_path = "/opt/airflow/dags/shared_data.txt"
        with open(file_path, "r") as f:
            data = f.read()
        print(f"Consumer is processing data: '{data}'")
        print("Processing completed successfully!")

    process_data()

consumer_physical_dag()